"""Add auth sub id to user model

Revision ID: 6421e5855f7d
Revises: a98601c15a9e
Create Date: 2026-02-05 23:54:25.236425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6421e5855f7d'
down_revision = 'a98601c15a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_id', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['auth0_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth0_id')

    # ### end Alembic commands ###
