"""Remove legend column from Deck

Revision ID: 792d4b6f7c47
Revises: c196eafc95b5
Create Date: 2025-10-29 00:25:14.589568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792d4b6f7c47'
down_revision = 'c196eafc95b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_column('legend')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legend', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
