"""add foil_collection to user model

Revision ID: 8d468cd65a21
Revises: 6421e5855f7d
Create Date: 2026-02-28 00:23:54.917030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d468cd65a21'
down_revision = '6421e5855f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foil_collection', sa.JSON(), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('foil_collection')

    # ### end Alembic commands ###
